name: Checker

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - master
      - release/*
      - develop

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    env:
        Name: "Малахов Даниил Сергеевич"
        Group: "M33112"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print personal information
      run: |
        echo "ФИО: ${{ env.Name }}"
        echo "Номер группы: ${{ env.Group }}"
        echo "Github Nick: ${{ github.actor }}"

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests using pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Check code style with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Format code with black (if needed)
      run: |
        pip install black
        black --check .

    - name: Auto-format code with black (if needed)
      run: |
        pip install black
        black .
